import React from 'react'
import EducationCard from './EducationCard'

type Props = {}

const Education = (props: Props) => {

    const projects = [
        {
            id: 1,
            title: 'Food Ordering System',
            description: "A comprehensive platform that allows users to browse a variety of food items, customize their orders, and track delivery in real-time. The system features user authentication, payment integration, and an intuitive UI for seamless interaction.",
            link: "https://www.foodOrdering.com",
            technology: ["React.js", "Tailwind CSS", "MongoDB", "Node.js", "Express.js"]
        },
        {
            id: 2,
            title: 'E-Commerce Marketplace',
            description: "An online marketplace that connects buyers and sellers, offering a range of products across various categories. The platform supports secure transactions, real-time chat between users, and a powerful search algorithm to improve the shopping experience.",
            link: "https://www.ecommerceMarketplace.com",
            technology: ["Next.js", "Redux", "Firebase", "Stripe API", "Material-UI"]
        },
        {
            id: 3,
            title: 'Project Management Tool',
            description: "A project management application designed to help teams plan, track, and collaborate on projects. It includes features such as task assignment, deadline tracking, file sharing, and real-time notifications to enhance team productivity.",
            link: "https://www.projectManagementTool.com",
            technology: ["Angular", "NgRx", "Node.js", "GraphQL", "PostgreSQL"]
        },
        {
            id: 4,
            title: 'Social Media Platform',
            description: "A social networking site that enables users to connect with friends, share updates, and engage in discussions. The platform includes real-time messaging, multimedia sharing, and a personalized feed generated by a custom algorithm.",
            link: "https://www.socialMediaPlatform.com",
            technology: ["Vue.js", "Vuex", "Django", "SQLite", "Socket.io"]
        },
        {
            id: 5,
            title: 'Online Learning Portal',
            description: "An e-learning platform that offers a variety of courses in multiple domains. It features a user-friendly interface, video streaming, progress tracking, and interactive quizzes to ensure an engaging learning experience.",
            link: "https://www.onlineLearningPortal.com",
            technology: ["React.js", "Apollo Client", "GraphQL", "AWS S3", "Tailwind CSS"]
        }
    ];

    return (
        <section className="bg-teal-800 text-white">
            <div className="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8 lg:py-16">
                <div className="mx-auto max-w-lg text-center">
                    <h2 className="text-3xl font-bold sm:text-4xl">Projects and Works</h2>
                </div>

                <div className="mt-8 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
                    {projects && projects.map((project, index) => (
                        <EducationCard project={project} key={index} />
                    ))}
                </div>
            </div>
        </section>
    )
}

export default Education